extends SceneTree

const Campaign = preload("res://core/campaign_rules.gd")
const Battle = preload("res://core/battle_rules.gd")
const Characters = preload("res://core/character_rules.gd")
const Equipment = preload("res://core/equipment_rules.gd")
const Saves = preload("res://core/save_store.gd")

const FIXTURE_DIR := "res://tests/fixtures/character_legacy"
const ROUND_TRIP_DIR := "user://qa/progression_regression"

var checks := 0
var failures: Array[String] = []


func _initialize() -> void:
	_cleanup_round_trips()
	_test_fixture_contracts()
	_test_legacy_migration_and_stability()
	_test_old_pending_growth_is_not_rerolled()
	_test_four_attribute_transactions()
	_test_training_transactions()
	_test_growth_survives_weapon_swaps()
	_test_equipment_does_not_change_progression_caps()
	_test_character_validation_rejects_malformed_progression()
	_test_beast_handler_is_learned_capability()
	_test_battle_experience_is_claimed_once()
	_cleanup_round_trips()
	print("Progression regression: %d checks; %d failures" % [checks, failures.size()])
	for failure in failures:
		printerr("FAIL: " + failure)
	quit(0 if failures.is_empty() else 1)


func check(value: bool, label: String) -> void:
	checks += 1
	if not value:
		failures.append(label)


func _test_fixture_contracts() -> void:
	var manifests := [_read_json(FIXTURE_DIR + "/manifest_v014.json"), _read_json(FIXTURE_DIR + "/manifest_v011.json")]
	for manifest: Dictionary in manifests:
		check(manifest.has_all(["source_commit", "save_rules_version", "fixtures"]), "legacy manifest identifies its committed source and fixtures")
		for fixture_name in manifest.get("fixtures", {}):
			var expected: Dictionary = manifest.fixtures[fixture_name]
			check(expected.has_all(["phase", "campaign_rng_state", "resources", "roster_legacy", "history", "claimed", "event", "growth_unit_id", "growth_offers", "battle", "battle_sha256"]), "%s manifest keeps every critical migration expectation" % fixture_name)
			check(FileAccess.file_exists(FIXTURE_DIR + "/" + str(fixture_name) + ".json"), "%s checksummed legacy save is included in the repository" % fixture_name)
	var v014: Dictionary = manifests[0].get("fixtures", {})
	check(v014.has_all(["camp_v014", "event_v014", "battle_v014", "growth_v014", "returning_v014"]), "0.1.4 fixtures cover all five required campaign phases")
	check(str(v014.get("battle_v014", {}).get("battle", {}).get("rules_version", "")) == "prototype-0.1.4", "active 0.1.4 battle fixture records its actual rules version")
	check(str(manifests[1].get("fixtures", {}).get("battle_v011", {}).get("battle", {}).get("rules_version", "")) == "prototype-0.1.1", "0.1.1 fixture was generated by the actual prior battle rules")


func _test_legacy_migration_and_stability() -> void:
	var all_expected := {}
	for manifest_name in ["manifest_v014.json", "manifest_v011.json"]:
		var manifest := _read_json(FIXTURE_DIR + "/" + manifest_name)
		for fixture_name in manifest.get("fixtures", {}):
			all_expected[fixture_name] = manifest.fixtures[fixture_name]
	for fixture_name in all_expected:
		var expected: Dictionary = all_expected[fixture_name]
		var loaded := Saves.load_campaign(FIXTURE_DIR + "/" + str(fixture_name) + ".json")
		check(loaded.get("ok", false), "%s loads through the current save migration" % fixture_name)
		check(loaded.get("upgraded", false), "%s explicitly reports a one-time upgrade" % fixture_name)
		if not loaded.get("ok", false):
			continue
		var c: Dictionary = loaded.campaign
		_check_legacy_expectations(str(fixture_name), c, expected)
		check(Characters.validate_campaign(c).is_empty(), "%s has a complete valid character ledger after migration" % fixture_name)
		var migrated_once := JSON.stringify(c)
		Characters.ensure_campaign(c)
		check(JSON.stringify(c) == migrated_once, "%s repeated character migration is idempotent" % fixture_name)
		var round_trip_path := ROUND_TRIP_DIR + "/" + str(fixture_name) + ".json"
		_remove_save(round_trip_path)
		check(Saves.save_campaign(c, round_trip_path).get("ok", false), "%s upgraded state can be saved" % fixture_name)
		var reloaded := Saves.load_campaign(round_trip_path)
		check(reloaded.get("ok", false) and not reloaded.get("upgraded", true), "%s upgraded state does not migrate a second time" % fixture_name)
		check(reloaded.get("ok", false) and reloaded.campaign == c, "%s upgraded state round-trips exactly" % fixture_name)


func _check_legacy_expectations(fixture_name: String, c: Dictionary, expected: Dictionary) -> void:
	check(str(c.get("phase", "")) == str(expected.phase), fixture_name + " preserves phase")
	check(int(c.get("rng_state", -1)) == int(expected.campaign_rng_state), fixture_name + " preserves campaign RNG")
	check({"gold": int(c.gold), "food": int(c.food), "day": int(c.day), "renown": int(c.renown)} == expected.resources, fixture_name + " preserves resources and time")
	check(c.history == expected.history, fixture_name + " preserves campaign history")
	check(c.claimed == expected.claimed, fixture_name + " preserves unique settlement claims")
	if expected.has("equipment"):
		check(c.event == expected.event, fixture_name + " preserves generated event and selected choice")
	else:
		check(_contains_legacy_value(c.event, expected.event), fixture_name + " preserves every old event field while adding required world metadata")
	check(str(c.growth_unit_id) == str(expected.growth_unit_id) and c.growth_offers == expected.growth_offers, fixture_name + " preserves pending growth target and candidates without reroll")
	_check_legacy_roster(fixture_name, c.roster, expected.roster_legacy)
	if expected.has("equipment"):
		check(c.equipment == expected.equipment, fixture_name + " preserves equipment instances, loadouts and armor durability")
	var old_battle: Dictionary = expected.battle
	if not old_battle.is_empty():
		check(c.battle == old_battle, fixture_name + " preserves the complete battle snapshot byte-for-byte semantically")
		check(JSON.stringify(c.battle).sha256_text() == str(expected.battle_sha256), fixture_name + " preserves battle key order and canonical JSON fingerprint")
		check(int(c.battle.rng_state) == int(old_battle.rng_state), fixture_name + " preserves battle RNG")
		check(c.battle.action_log == old_battle.action_log and c.battle.log == old_battle.log, fixture_name + " preserves action and readable combat logs")
		check(c.battle.units == old_battle.units and c.battle.initial_roster == old_battle.initial_roster, fixture_name + " preserves battle units and initial roster")


func _check_legacy_roster(fixture_name: String, roster: Array, expected_roster: Array) -> void:
	check(roster.size() == expected_roster.size(), fixture_name + " preserves roster size")
	for expected_unit: Dictionary in expected_roster:
		var unit := _find_unit(roster, str(expected_unit.id))
		check(not unit.is_empty(), "%s preserves character %s" % [fixture_name, str(expected_unit.id)])
		if unit.is_empty():
			continue
		for key in ["name", "kind", "hp", "max_hp", "armor", "max_armor", "attack", "accuracy", "range", "perks"]:
			check(unit.get(key) == expected_unit.get(key), "%s/%s preserves old effective %s" % [fixture_name, str(expected_unit.id), key])
		if expected_unit.has("equipment"):
			check(unit.equipment == expected_unit.equipment and str(unit.weapon_style) == str(expected_unit.weapon_style) and unit.visual_loadout == expected_unit.visual_loadout, "%s/%s preserves equipped IDs and visuals" % [fixture_name, str(expected_unit.id)])


func _test_old_pending_growth_is_not_rerolled() -> void:
	var loaded := Saves.load_campaign(FIXTURE_DIR + "/growth_v014.json")
	check(loaded.get("ok", false), "old pending-growth fixture loads")
	if not loaded.get("ok", false):
		return
	var c: Dictionary = loaded.campaign
	var offers: Array = c.growth_offers.duplicate(true)
	var rng_before := int(c.rng_state)
	var offer_id := str(offers[0].id)
	check(Campaign.choose_growth(c, offer_id).get("ok", false), "saved old growth offer remains redeemable")
	check(str(c.phase) == "returning" and c.growth_offers.is_empty() and int(c.rng_state) == rng_before, "redeeming old growth clears it once without consuming RNG")
	var once := JSON.stringify(c)
	check(not Campaign.choose_growth(c, offer_id).get("ok", false) and JSON.stringify(c) == once, "old growth offer cannot be claimed twice")


func _test_four_attribute_transactions() -> void:
	var c := Campaign.create_campaign("free", 51001)
	var view := Characters.get_view(c, "crew_1")
	var ids: Array = []
	for stat: Dictionary in view.get("stats", []):
		ids.append(str(stat.id))
	check(ids == ["vitality", "melee_skill", "ranged_skill", "defense"], "character view exposes the four accepted attributes in stable order")
	var unit: Dictionary = _find_unit(c.roster, "crew_1")
	unit.hp = int(unit.max_hp) - 7
	unit.progression.attribute_points = 4
	var old_max := int(unit.max_hp)
	var old_hp := int(unit.hp)
	var old_melee := int(unit.melee_skill)
	var old_ranged := int(unit.ranged_skill)
	var old_defense := int(unit.defense)
	for stat_id in ["vitality", "melee_skill", "ranged_skill", "defense"]:
		check(Characters.spend_attribute(c, "crew_1", stat_id).get("ok", false), "attribute point can be spent on " + stat_id)
	check(int(unit.progression.attribute_points) == 0, "four upgrades consume exactly four attribute points")
	check(int(unit.max_hp) == old_max + 6 and int(unit.hp) == old_hp + 6 and int(unit.max_hp) - int(unit.hp) == 7, "vitality growth preserves existing missing HP")
	check(int(unit.melee_skill) == old_melee + 4 and int(unit.ranged_skill) == old_ranged + 4 and int(unit.defense) == old_defense + 3, "melee, ranged and defense use their declared upgrade amounts")
	var spent := JSON.stringify(c)
	check(not Characters.spend_attribute(c, "crew_1", "defense").get("ok", false) and JSON.stringify(c) == spent, "spending without a point is an atomic rejection")


func _test_training_transactions() -> void:
	var c := Campaign.create_campaign("free", 51002)
	var unit: Dictionary = _find_unit(c.roster, "crew_2")
	var old_day := int(c.day)
	var old_food := int(c.food)
	var old_ranged := int(unit.ranged_skill)
	check(Characters.train(c, "crew_2", "basic_ranged").get("ok", false), "camp training accepts a living human with one practice credit")
	check(int(c.day) == old_day + 1 and int(c.food) == old_food - 1 and int(unit.progression.training_credits) == 0, "training charges one day, one ration and one credit exactly once")
	check(int(unit.ranged_skill) == old_ranged + 2 and unit.progression.training_claims.size() == 1 and unit.progression.stat_changes.size() == 1, "training records its stable claim and stat source")
	var once := JSON.stringify(c)
	check(not Characters.train(c, "crew_2", "basic_ranged").get("ok", false) and JSON.stringify(c) == once, "training cannot repeat without another practice credit")
	c.phase = "event"
	unit.progression.training_credits = 1
	var outside_camp := JSON.stringify(c)
	check(not Characters.train(c, "crew_2", "basic_defense").get("ok", false) and JSON.stringify(c) == outside_camp, "training outside camp is blocked without partial cost")


func _test_growth_survives_weapon_swaps() -> void:
	var c := Campaign.create_campaign("free", 51003)
	var unit: Dictionary = _find_unit(c.roster, "crew_1")
	unit.progression.attribute_points = 1
	check(Characters.spend_attribute(c, "crew_1", "melee_skill").get("ok", false), "weapon-swap fixture gains melee growth")
	var growth_before: Dictionary = unit.stat_sources.growth.duplicate(true)
	var original_weapon := str(unit.equipment.weapon)
	var original_accuracy := int(unit.accuracy)
	var original_attack := int(unit.attack)
	var purchase := Equipment.buy(c, "weapon_guard_cleaver")
	check(purchase.get("ok", false), "weapon-swap fixture buys a modified weapon")
	if not purchase.get("ok", false):
		return
	var modified_weapon := str(purchase.instance_id)
	check(Equipment.equip(c, "crew_1", modified_weapon).get("ok", false), "modified weapon equips")
	check(int(unit.accuracy) == original_accuracy - 5 and int(unit.attack) == original_attack + 3, "weapon modifiers apply once on top of trained stats")
	check(Equipment.equip(c, "crew_1", original_weapon).get("ok", false), "original weapon re-equips")
	check(int(unit.accuracy) == original_accuracy and int(unit.attack) == original_attack and unit.stat_sources.growth == growth_before, "switching back restores exact trained values without losing growth")
	check(Equipment.equip(c, "crew_1", modified_weapon).get("ok", false) and Equipment.equip(c, "crew_1", original_weapon).get("ok", false), "repeated swaps remain legal")
	check(int(unit.accuracy) == original_accuracy and int(unit.attack) == original_attack and unit.stat_sources.growth == growth_before, "repeated swaps do not drift stats")


func _test_equipment_does_not_change_progression_caps() -> void:
	var c := Campaign.create_campaign("free", 51006)
	var unit: Dictionary = _find_unit(c.roster, "crew_1")
	unit.progression.attribute_points = 6
	for unused in range(5):
		check(Characters.spend_attribute(c, "crew_1", "melee_skill").get("ok", false), "permanent melee growth can reach 108 below its 110 cap")
	var permanent_before := int(unit.stat_sources.base.melee_skill) + int(unit.stat_sources.growth.melee_skill) + int(unit.stat_sources.compatibility.melee_skill) + int(unit.stat_sources.perk.melee_skill)
	check(permanent_before == 108, "cap fixture has 108 permanent melee skill before equipment")
	var original_weapon := str(unit.equipment.weapon)
	var purchase := Equipment.buy(c, "weapon_guard_cleaver")
	check(purchase.get("ok", false) and Equipment.equip(c, "crew_1", str(purchase.instance_id)).get("ok", false), "cap fixture equips a -5 accuracy weapon")
	var before_over_cap := JSON.stringify(c)
	check(not Characters.spend_attribute(c, "crew_1", "melee_skill").get("ok", false) and JSON.stringify(c) == before_over_cap, "negative equipment cannot open a permanent upgrade beyond the 110 cap")
	check(Equipment.equip(c, "crew_1", original_weapon).get("ok", false) and int(unit.melee_skill) <= 110, "removing negative equipment cannot reveal permanent skill above the cap")

	var hunters := Campaign.create_campaign("hunters", 51007)
	var ranged: Dictionary = _find_unit(hunters.roster, "crew_3")
	ranged.stat_sources.growth.ranged_skill = 20
	Characters.recompute_character(ranged, hunters)
	var recurve := Equipment.buy(hunters, "weapon_hunter_recurve")
	check(recurve.get("ok", false) and Equipment.equip(hunters, "crew_3", str(recurve.instance_id)).get("ok", false), "cap fixture equips a +7 accuracy weapon at 108 permanent ranged skill")
	check(Characters.train(hunters, "crew_3", "basic_ranged").get("ok", false), "positive equipment does not block legal permanent training from 108 to the 110 cap")
	check(int(ranged.stat_sources.growth.ranged_skill) == 22, "legal capped training records its permanent +2 despite temporary equipment bonus")


func _test_character_validation_rejects_malformed_progression() -> void:
	var c := Campaign.create_campaign("free", 51008)
	var negative_xp := c.duplicate(true)
	negative_xp.roster[0].progression.xp = -1
	negative_xp.roster[0].progression.level = 1
	negative_xp.roster[0].level = 1
	check(not Saves.validate(negative_xp).is_empty(), "save validation rejects negative XP even when the derived level is still one")

	var fractional_points := c.duplicate(true)
	fractional_points.roster[0].progression.attribute_points = 0.5
	check(not Saves.validate(fractional_points).is_empty(), "save validation rejects non-integer attribute points")

	var missing_growth := c.duplicate(true)
	missing_growth.roster[0].stat_sources.erase("growth")
	check(not Saves.validate(missing_growth).is_empty(), "save validation rejects a missing growth source bucket")

	var missing_growth_stat := c.duplicate(true)
	missing_growth_stat.roster[0].stat_sources.growth.erase("defense")
	check(not Saves.validate(missing_growth_stat).is_empty(), "save validation rejects a growth bucket missing one accepted stat")


func _test_beast_handler_is_learned_capability() -> void:
	var c := Campaign.create_campaign("hunters", 51004)
	var learner: Dictionary = _find_unit(c.roster, "crew_1")
	var old_handler: Dictionary = _find_unit(c.roster, "crew_3")
	var dog: Dictionary = _find_unit(c.roster, "crew_4")
	check(str(dog.get("hunter_id", "")) == "crew_3", "hunter origin starts with the existing dog binding")
	check(Characters.train(c, "crew_1", "beast_handler").get("ok", false), "non-hunter can learn beast handling at camp")
	check("beast_handler" in learner.capability_tags and str(learner.kind) == "guard", "learned beast capability does not rewrite background kind")
	check(Characters.train(c, "crew_1", "bind_dog").get("ok", false), "trained non-hunter can take over the existing dog")
	check(str(dog.hunter_id) == "crew_1" and str(learner.get("beast_id", "")) == "crew_4" and str(old_handler.get("beast_id", "")).is_empty(), "dog has exactly one current handler after reassignment")
	var battle := Battle.create_battle(c.roster, 51004, {"id": "capability_fixture"})
	var actions := Battle.get_actions(battle, "crew_1")
	check(_has_action(actions, "mark") and _has_action(actions, "command_follow") and _has_action(actions, "command_pin") and _has_action(actions, "command_recall"), "battle actions follow learned beast capability instead of hunter kind")
	check("packbond" in Campaign._eligible_perks(learner), "beast synergy eligibility follows capability instead of dog kind")
	var archer: Dictionary = _find_unit(c.roster, "crew_3")
	var spear_purchase := Equipment.buy(c, "weapon_spear_hooked")
	check(spear_purchase.get("ok", false) and Equipment.equip(c, str(archer.id), str(spear_purchase.instance_id)).get("ok", false), "different background can equip the same spear prerequisite")
	check("breacher" in Campaign._eligible_perks(archer), "perk eligibility follows equipped spear instead of original kind")
	var once := JSON.stringify(c)
	check(not Characters.train(c, "crew_1", "bind_dog").get("ok", false) and JSON.stringify(c) == once, "rebinding the already owned dog is rejected atomically")


func _test_battle_experience_is_claimed_once() -> void:
	var c := Campaign.create_campaign("free", 51005)
	_ready(c)
	var battle := Battle.create_battle(c.roster, int(c.seed) + int(c.expedition.index) * 7919, Campaign.battle_config(c))
	check(Campaign.begin_battle(c, battle).get("ok", false), "experience fixture begins a registered battle")
	var actor := Battle.active_unit(c.battle)
	check(Battle.apply_action(c.battle, str(actor.id), "oil", {"q": int(actor.q), "r": int(actor.r)}).get("ok", false), "experience fixture records meaningful participation")
	for unit: Dictionary in c.battle.units:
		if str(unit.team) == "enemy":
			unit.hp = 0
	c.battle.outcome = "victory"
	var xp_before := {}
	for unit: Dictionary in c.roster:
		xp_before[str(unit.id)] = int(unit.progression.xp)
	check(Campaign.resolve_battle(c, c.battle).get("ok", false), "victory settles progression with the battle claim")
	for unit: Dictionary in c.roster:
		check(int(unit.progression.xp) == int(xp_before[str(unit.id)]) + 100 and int(unit.progression.level) == 2 and int(unit.progression.attribute_points) == 2, "%s receives shared victory XP and one level exactly once" % str(unit.id))
	var settled := JSON.stringify(c)
	check(not Campaign.resolve_battle(c, c.battle).get("ok", false) and JSON.stringify(c) == settled, "duplicate battle settlement cannot award XP or rewards twice")
	var path := ROUND_TRIP_DIR + "/experience.json"
	_remove_save(path)
	check(Saves.save_campaign(c, path).get("ok", false), "settled experience can save")
	var loaded := Saves.load_campaign(path)
	var difference := "load failed" if not loaded.get("ok", false) else _first_difference(c, loaded.campaign)
	check(loaded.get("ok", false) and loaded.campaign == c, "settled XP, levels, points and claim IDs round-trip exactly; " + difference)


func _ready(c: Dictionary) -> void:
	check(Campaign.start_expedition(c, "road").get("ok", false), "experience fixture starts expedition")
	while str(c.phase) == "travel":
		check(Campaign.advance_travel(c).get("ok", false), "experience fixture advances travel")
	if str(c.phase) == "event":
		check(Campaign.choose_event(c, str(c.event.choices[0].id)).get("ok", false), "experience fixture resolves event")
	while str(c.phase) == "travel":
		check(Campaign.advance_travel(c).get("ok", false), "experience fixture reaches destination")
	check(str(c.phase) == "ready", "experience fixture reaches battle ready phase")


func _read_json(path: String) -> Dictionary:
	var file := FileAccess.open(path, FileAccess.READ)
	check(file != null, path + " can be read")
	if file == null:
		return {}
	var parser := JSON.new()
	var error := parser.parse(file.get_as_text())
	file.close()
	check(error == OK and parser.data is Dictionary, path + " is valid JSON")
	if error != OK or not parser.data is Dictionary:
		return {}
	return _canonicalize_numbers(parser.data)


func _canonicalize_numbers(value: Variant) -> Variant:
	if value is Dictionary:
		var dictionary: Dictionary = value
		for key in dictionary.keys():
			dictionary[key] = _canonicalize_numbers(dictionary[key])
		return dictionary
	if value is Array:
		var array: Array = value
		for i in range(array.size()):
			array[i] = _canonicalize_numbers(array[i])
		return array
	if value is float and is_finite(value) and value == floor(value):
		return int(value)
	return value


func _find_unit(roster: Array, unit_id: String) -> Dictionary:
	for unit: Dictionary in roster:
		if str(unit.get("id", "")) == unit_id:
			return unit
	return {}


func _has_action(actions: Array, action_id: String) -> bool:
	for action: Dictionary in actions:
		if str(action.get("id", "")) == action_id:
			return true
	return false


func _contains_legacy_value(actual: Variant, expected: Variant) -> bool:
	if expected is Dictionary:
		if not actual is Dictionary:
			return false
		for key in expected:
			if not actual.has(key) or not _contains_legacy_value(actual[key], expected[key]):
				return false
		return true
	if expected is Array:
		if not actual is Array or actual.size() != expected.size():
			return false
		for i in range(expected.size()):
			if not _contains_legacy_value(actual[i], expected[i]):
				return false
		return true
	return actual == expected


func _first_difference(left: Variant, right: Variant, path: String = "campaign") -> String:
	if left is Dictionary and right is Dictionary:
		for key in left:
			if not right.has(key):
				return path + " missing right key " + str(key)
			var nested := _first_difference(left[key], right[key], path + "." + str(key))
			if not nested.is_empty():
				return nested
		for key in right:
			if not left.has(key):
				return path + " has new right key " + str(key)
		return ""
	if left is Array and right is Array:
		if left.size() != right.size():
			return "%s size %d != %d" % [path, left.size(), right.size()]
		for i in range(left.size()):
			var nested := _first_difference(left[i], right[i], "%s[%d]" % [path, i])
			if not nested.is_empty():
				return nested
		return ""
	if left != right or typeof(left) != typeof(right):
		return "%s differs: %s (%s) != %s (%s)" % [path, str(left), type_string(typeof(left)), str(right), type_string(typeof(right))]
	return ""


func _cleanup_round_trips() -> void:
	for name in ["camp_v014", "event_v014", "battle_v014", "growth_v014", "returning_v014", "battle_v011", "experience"]:
		_remove_save(ROUND_TRIP_DIR + "/" + name + ".json")


func _remove_save(path: String) -> void:
	for suffix in ["", ".tmp", ".bak", ".bak.tmp"]:
		var candidate: String = path + suffix
		if FileAccess.file_exists(candidate):
			DirAccess.remove_absolute(candidate)
